### ISSUE TITLE
Add Record ID

### ISSUE THREAD

**Issue by PenelopeRammos** [IBMPredictiveAnalytics/TWCo_Historical_Gridded#1]
Hi Wenpei, I am so glad someone decided to make the API call from the weather company into a custom SPSS modeler node! Thank you! One improvement could be to add the record ID as an input field (and output field) in the node. 

Currently to merge the weather data with your original records you have to use the lat/long coordinates and date time fields as merging keys. However, I noticed some small changes in the outputted coordinate decimals making it very hard to merge to the original data set. Not sure if it is an SPSS modeler to R issue or not, but I made sure to input lat/longs with 5 decimal points exactly. Somehow the longitude values (not the latitude) returned with 6 digits... not sure why. If you need screenshots or more explanation on this let me know :)

**Comment by Wenpei** [comment]
@PenelopeRammos thanks for raise this :-)
Please send me this detail stream. yuwenp@cn.ibm.com

I remember I add input lat/longs to output data which named "inputLatitude","inputLongitude". This should be merge key, are you mean this column has different decimal points with original input?

**Comment by Wenpei** [comment]
After discuss, we would mark this as "no plan to fix" since "inputLatitude""inputLongitude" will be good as merge key.
