### ISSUE TITLE
Bad url called in R code?

### ISSUE THREAD

**Issue by timtom27** [IBMPredictiveAnalytics/TWCo_Historical_Gridded#2]
When I run the node against a zip code I get errors like this one below in the console output. It seems the extension isn't calling out the correct url

PostalCode 
     53989 
[1] "http://cleanedobservations.wsi.com/CleanedObs.svc/GetObs?version=2&format=csv&zipcode=53989&startDate=02/01/2016&endDate=02/02/2016&userKey=3362063a8c9071261b0c5918d41974a9&interval=hourly&units=metric&station=cfsr&time=gmt"
Error in file(url, "r") : cannot open the connection
In addition: Warning message:
In file(url, "r") :
  cannot open URL 'http://cleanedobservations.wsi.com/CleanedObs.svc/GetObs?version=2&format=csv&zipcode=53989&startDate=02/01/2016&endDate=02/02/2016&userKey=3362063a8c9071261b0c5918d41974a9&interval=hourly&units=metric&station=cfsr&time=gmt': HTTP status was '400 Bad Request'
[1] 0
[1] 0
Error in data.frame(inputlocationid = modelerDataIter[input_col_zipcode],  : 
  arguments imply differing number of rows: 1, 0
Error:  IBM SPSS CF error:  The error code is '1012'  With message 'Data and data model does not match.'

**Comment by Wenpei** [comment]
@timtom27 
It's you api key issues I guess.
Historical API is different with other TWC api. Please contact TWC support for detail information.
